### ISSUE TITLE
Unable to sync config: hook_config_info() not implemented

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/better_search#1]
Hello and thank you for this great module :)

I am unable to sync config on my site with this module installed because it uses a config file that has not been registered. This is the error I see:

```
The configuration "better_search.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.
```

PR coming.

**Comment by laryn** [comment]
Thank you, I've merged the PR!
